apiVersion: v1
kind: Service
metadata:
  name: bluescope-api-workbench
  labels:
    app.kubernetes.io/name: bluescope-api-workbench
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bluescope-api-workbench
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31823
