apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gitrepository.yaml
  - flux-system/kustomization.yaml
  - tertius/namespace.yaml
  - tertius/helmrelease.yaml
