import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { CompilerTab } from './CompilerTab'

const storage = vi.hoisted(() => ({
  getActiveProject: vi.fn(),
  listFiles: vi.fn(),
  loadCode: vi.fn(),
  saveCode: vi.fn(),
  deleteFile: vi.fn(),
  getStatus: vi.fn(),
  getHistory: vi.fn(),
}))

const mocks = vi.hoisted(() => ({
  apiFetch: vi.fn(),
  getAccessToken: vi.fn(),
}))

vi.mock('../../../api/client', () => ({
  apiFetch: mocks.apiFetch,
}))

vi.mock('../../../auth/AuthProvider', () => ({
  useAuth: () => ({
    authMode: 'authenticated',
    getAccessToken: mocks.getAccessToken,
  }),
}))

vi.mock('../../shared/projectStorage', () => ({
  createProjectStorage: () => storage,
}))

vi.mock('@monaco-editor/react', () => ({
  default: ({ value, onChange }: { value: string; onChange: (value: string) => void }) => (
    <textarea aria-label="code editor" value={value} onChange={(event) => onChange(event.currentTarget.value)} />
  ),
}))

function jsonResponse(data: unknown, ok = true) {
  return {
    ok,
    json: vi.fn().mockResolvedValue(data),
  }
}

async function renderCompiler(isActive = false) {
  render(<CompilerTab serverUrl="/api/intus" isActive={isActive} />)
  await screen.findByText('default_purlin')
  await act(async () => {})
}

describe('CompilerTab compile jobs', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    for (const mock of Object.values(storage)) {
      mock.mockReset()
    }
    mocks.apiFetch.mockReset()
    mocks.getAccessToken.mockReset()
    storage.getActiveProject.mockResolvedValue('default_purlin')
    storage.listFiles.mockResolvedValue(['design.py'])
    storage.loadCode.mockResolvedValue('box = Box(1, 1, 1)')
    storage.saveCode.mockResolvedValue(undefined)
    storage.deleteFile.mockResolvedValue(undefined)
    storage.getStatus.mockResolvedValue({ mtime: 42 })
    storage.getHistory.mockResolvedValue({ is_git: true, history: [] })
  })

  afterEach(() => {
    cleanup()
    vi.useRealTimers()
  })

  it('manual compile starts a job, polls status, then logs success', async () => {
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-1',
        status: 'succeeded',
        format: 'glb',
        artifact_id: 'artifact-1',
      }))

    await renderCompiler()
    vi.useFakeTimers()

    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))

    await act(async () => {})
    expect(mocks.apiFetch).toHaveBeenCalledWith(
      '/api/intus/projects/default_purlin/compile',
      mocks.getAccessToken,
      expect.objectContaining({ method: 'POST' }),
    )
    expect(screen.getByText(/Compile queued/)).toBeInTheDocument()

    await act(async () => {
      await vi.advanceTimersByTimeAsync(1000)
    })

    expect(mocks.apiFetch).toHaveBeenCalledWith(
      '/api/intus/projects/default_purlin/compile/jobs/job-1',
      mocks.getAccessToken,
    )
    expect(screen.getByText(/Compiled glb artifact artifact-1/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Compile & Export/i })).toBeEnabled()
  })

  it('failed job polling shows user guidance, technical details, and try again without auto retrying', async () => {
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-1',
        status: 'failed',
        format: 'glb',
        error_code: 'sandbox_error',
        user_message: 'Compile failed. Fix the model source and try again.',
        error: 'RuntimeError: No 3D shapes were generated by the script.',
        retryable: true,
      }))

    await renderCompiler()
    vi.useFakeTimers()

    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))
    await act(async () => {})
    await act(async () => {
      await vi.advanceTimersByTimeAsync(1000)
    })

    expect(screen.getByText(/Compile failed/)).toBeInTheDocument()
    expect(screen.getByText(/Fix the model source and try again/)).toBeInTheDocument()
    expect(screen.getByText(/RuntimeError: No 3D shapes were generated/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Try again/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Compile & Export/i })).toBeEnabled()
    expect(mocks.apiFetch).toHaveBeenCalledTimes(2)
  })

  it('stops polling and surfaces non-ok job status responses', async () => {
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({ error: 'Compile job not found' }, false))

    await renderCompiler()
    vi.useFakeTimers()

    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))
    await act(async () => {})
    await act(async () => {
      await vi.advanceTimersByTimeAsync(1000)
    })
    await act(async () => {
      await vi.advanceTimersByTimeAsync(3000)
    })

    expect(screen.getByText(/Compile job not found/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Compile & Export/i })).toBeEnabled()
    expect(mocks.apiFetch).toHaveBeenCalledTimes(2)
  })

  it('shows retry affordance when queueing returns a retryable failure job', async () => {
    mocks.apiFetch.mockResolvedValueOnce(jsonResponse({
      success: false,
      job_id: 'job-1',
      short: 'Failed to enqueue compile job',
      user_message: 'Compile could not be started. Try again.',
      retryable: true,
    }, false))

    await renderCompiler()

    fireEvent.change(screen.getByLabelText('code editor'), { target: { value: 'box = Box(2, 2, 2)' } })
    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))
    await act(async () => {})

    expect(screen.getByText(/Compile could not be started/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Try again/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Compile & Export/i })).toBeEnabled()
  })

  it('try again posts current editor contents and polls the new job', async () => {
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-1',
        status: 'failed',
        format: 'glb',
        user_message: 'Compile failed. Fix the model source and try again.',
        error: 'RuntimeError: No 3D shapes were generated by the script.',
        retryable: true,
      }))
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-2', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-2',
        status: 'succeeded',
        format: 'glb',
        artifact_id: 'artifact-2',
      }))

    await renderCompiler()
    vi.useFakeTimers()

    fireEvent.change(screen.getByLabelText('code editor'), { target: { value: 'box = Box(2, 2, 2)' } })
    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))
    await act(async () => {})
    await act(async () => {
      await vi.advanceTimersByTimeAsync(1000)
    })
    expect(screen.getByRole('button', { name: /Try again/i })).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: /Try again/i }))

    await act(async () => {})
    expect(mocks.apiFetch).toHaveBeenCalledTimes(3)
    const retryOptions = mocks.apiFetch.mock.calls[2][2]
    expect(JSON.parse(retryOptions.body)).toEqual(expect.objectContaining({
      code: 'box = Box(2, 2, 2)',
      export_format: 'glb',
      file: 'design.py',
    }))

    await act(async () => {
      await vi.advanceTimersByTimeAsync(1000)
    })

    expect(mocks.apiFetch).toHaveBeenCalledWith(
      '/api/intus/projects/default_purlin/compile/jobs/job-2',
      mocks.getAccessToken,
    )
    expect(screen.getByText(/Compiled glb artifact artifact-2/)).toBeInTheDocument()
  })

  it('auto-compile uses polling and disables auto-compile after a failed terminal status', async () => {
    storage.loadCode
      .mockResolvedValueOnce('box = Box(1, 1, 1)')
      .mockResolvedValueOnce('box = Box(3, 3, 3)')
    storage.getStatus
      .mockResolvedValueOnce({ mtime: 1 })
      .mockResolvedValueOnce({ mtime: 2 })
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-1',
        status: 'failed',
        format: 'glb',
        user_message: 'Compile failed. Fix the model source and try again.',
        error: 'RuntimeError: No 3D shapes were generated by the script.',
        retryable: true,
      }))

    await renderCompiler(true)

    await waitFor(() => {
      expect(mocks.apiFetch).toHaveBeenCalledWith(
        '/api/intus/projects/default_purlin/compile',
        mocks.getAccessToken,
        expect.objectContaining({ method: 'POST' }),
      )
    }, { timeout: 2500 })

    await waitFor(() => {
      expect(mocks.apiFetch).toHaveBeenCalledWith(
        '/api/intus/projects/default_purlin/compile/jobs/job-1',
        mocks.getAccessToken,
      )
      expect(screen.getByText(/Compile failed/)).toBeInTheDocument()
      expect(screen.getByLabelText('Auto-compile')).not.toBeChecked()
    }, { timeout: 2500 })
  })

  it('reloads a server-side edit that lands while a compile job is running', async () => {
    storage.loadCode
      .mockResolvedValueOnce('box = Box(1, 1, 1)')
      .mockResolvedValueOnce('box = Box(4, 4, 4)')
    storage.getStatus
      .mockResolvedValueOnce({ mtime: 1 })
      .mockResolvedValueOnce({ mtime: 2 })
      .mockResolvedValueOnce({ mtime: 2 })
    mocks.apiFetch
      .mockResolvedValueOnce(jsonResponse({ success: true, job_id: 'job-1', status: 'queued' }))
      .mockResolvedValueOnce(jsonResponse({
        job_id: 'job-1',
        status: 'succeeded',
        format: 'glb',
        artifact_id: 'artifact-1',
      }))

    await renderCompiler(true)

    await waitFor(() => {
      expect(storage.getStatus).toHaveBeenCalledTimes(1)
    }, { timeout: 1500 })

    fireEvent.click(screen.getByLabelText('Auto-compile'))
    fireEvent.click(screen.getByRole('button', { name: /Compile & Export/i }))
    await act(async () => {})

    await waitFor(() => {
      expect(screen.getByText(/Compiled glb artifact artifact-1/)).toBeInTheDocument()
    }, { timeout: 2500 })

    await waitFor(() => {
      expect(storage.loadCode).toHaveBeenCalledWith('default_purlin', 'design.py')
      expect(screen.getByLabelText('code editor')).toHaveValue('box = Box(4, 4, 4)')
    }, { timeout: 2500 })
  }, 10000)
})
