{{- if .Values.cloudflared.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tertius.fullname" . }}-cloudflared
  labels:
    {{- include "tertius.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudflared
spec:
  replicas: {{ .Values.cloudflared.replicaCount }}
  selector:
    matchLabels:
      {{- include "tertius.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cloudflared
  template:
    metadata:
      labels:
        {{- include "tertius.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cloudflared
    spec:
      serviceAccountName: {{ include "tertius.serviceAccountName" . }}
      containers:
        - name: cloudflared
          image: "{{ .Values.cloudflared.image.repository }}:{{ .Values.cloudflared.image.tag }}"
          imagePullPolicy: {{ .Values.cloudflared.image.pullPolicy }}
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudflared.tunnelTokenSecretName | quote }}
                  key: {{ .Values.cloudflared.tunnelTokenSecretKey | quote }}
          resources:
            {{- toYaml .Values.cloudflared.resources | nindent 12 }}
{{- end }}
