from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


SANDBOX_SCRIPT = r"""
import os
import sys
import traceback
from pathlib import Path

import build123d as bd

project_dir = Path.cwd()
export_format = sys.argv[1].lower()
output_path = project_dir / f"output.{export_format}"
env = {"bd": bd, "build123d": bd}

project_dir_str = str(project_dir.resolve())
if project_dir_str not in sys.path:
    sys.path.insert(0, project_dir_str)

try:
    design_file = project_dir / "design.py"
    if not design_file.exists():
        raise RuntimeError("design.py not found in project. Cannot compile.")

    exec(design_file.read_text(encoding="utf-8"), env)

    shapes = []
    for val in env.values():
        if isinstance(val, bd.Shape) and hasattr(val, "volume"):
            geom_type = val.geom_type() if callable(val.geom_type) else val.geom_type
            geom_name = getattr(geom_type, "name", str(geom_type)).upper()
            if geom_name in ("SOLID", "COMPOUND", "OTHER"):
                shapes.append(val)
        elif hasattr(val, "part") and isinstance(getattr(val, "part"), bd.Shape):
            shapes.append(val.part)

    if not shapes and hasattr(bd.BuildPart, "_get_context") and bd.BuildPart._get_context():
        shapes.append(bd.BuildPart._get_context().part)

    if not shapes:
        raise RuntimeError("No 3D shapes (Solid/Part) were generated by the script.")

    final_shapes = []
    seen = set()
    for shape in shapes:
        if id(shape) not in seen:
            seen.add(id(shape))
            final_shapes.append(shape)

    compound = bd.Compound(final_shapes) if len(final_shapes) > 1 else final_shapes[0]
    if export_format == "stl":
        bd.export_stl(compound, str(output_path))
    elif export_format == "step":
        bd.export_step(compound, str(output_path))
    elif export_format in ("gltf", "glb") and hasattr(bd, "export_gltf"):
        bd.export_gltf(compound, str(output_path), binary=(export_format == "glb"))

        if export_format == "glb":
            try:
                from build123d.exporters3d import _create_xde
                from OCP.XCAFDoc import XCAFDoc_DocumentTool
                from OCP.TCollection import TCollection_AsciiString
                from OCP.TDF import TDF_Tool
                import json
                import struct

                # 1. Map tags to labels
                original_location = compound.location
                compound.location *= bd.Location((0, 0, 0), (1, 0, 0), -90)
                doc = _create_xde(compound, getattr(bd, "Unit").MM)
                shape_tool = XCAFDoc_DocumentTool.ShapeTool_s(doc.Main())
                tag_to_name = {}

                for node in bd.PreOrderIter(compound):
                    if node.label:
                        inst_label = shape_tool.FindShape(node.wrapped, findInstance=True)
                        if inst_label.IsNull():
                            inst_label = shape_tool.FindShape(node.wrapped, findInstance=False)

                        if not inst_label.IsNull():
                            entry = TCollection_AsciiString()
                            TDF_Tool.Entry_s(inst_label, entry)
                            tag_to_name[f"=>[{entry.ToCString()}]"] = node.label

                compound.location = original_location

                # 2. Patch the .glb files
                def patch_glb_names(glb_path, mapping):
                    if not mapping:
                        return
                    with open(glb_path, "rb") as f:
                        data = f.read()

                    magic, version, length = struct.unpack("<4sII", data[:12])
                    if magic != b"glTF":
                        return

                    chunk_len, chunk_type = struct.unpack("<I4s", data[12:20])
                    if chunk_type != b"JSON":
                        return

                    json_data = data[20:20 + chunk_len].decode("utf-8")
                    gltf_json = json.loads(json_data)

                    changed = False
                    for node in gltf_json.get("nodes", []):
                        if node.get("name") in mapping:
                            node["name"] = mapping[node["name"]]
                            changed = True

                    if not changed:
                        return

                    new_json_data = json.dumps(gltf_json, separators=(',', ':')).encode("utf-8")
                    padding = (4 - len(new_json_data) % 4) % 4
                    new_json_data += b' ' * padding

                    new_chunk_len = len(new_json_data)
                    new_length = length - chunk_len + new_chunk_len

                    new_data = bytearray()
                    new_data.extend(struct.pack("<4sII", magic, version, new_length))
                    new_data.extend(struct.pack("<I4s", new_chunk_len, chunk_type))
                    new_data.extend(new_json_data)
                    new_data.extend(data[20 + chunk_len:])

                    with open(glb_path, "wb") as f:
                        f.write(new_data)

                patch_glb_names(str(output_path), tag_to_name)
            except Exception as patch_e:
                print("Failed to patch GLB names:", patch_e)
    else:
        raise RuntimeError(f"Unsupported export format: {export_format}")
except Exception:
    traceback.print_exc()
    sys.exit(1)
"""


@dataclass(frozen=True)
class CompileSandboxResult:
    success: bool
    output_path: Path | None
    stdout: str
    stderr: str
    error: str | None


def run_compile_sandbox(project_dir: Path, export_format: str, timeout_seconds: int = 30) -> CompileSandboxResult:
    ext = export_format.lower()
    output_path = project_dir / f"output.{ext}"
    try:
        result = subprocess.run(
            [sys.executable, "-c", SANDBOX_SCRIPT, ext],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=exc.stdout or "",
            stderr=exc.stderr or "",
            error=f"Compile timed out after {timeout_seconds} seconds",
        )

    if result.returncode != 0:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=result.stderr.strip() or f"Compile exited with status {result.returncode}",
        )

    if not output_path.exists():
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=f"Compile completed without creating output.{ext}",
        )

    return CompileSandboxResult(
        success=True,
        output_path=output_path,
        stdout=result.stdout,
        stderr=result.stderr,
        error=None,
    )
