from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


SANDBOX_SCRIPT = r"""
import os
import sys
import traceback
from pathlib import Path

import build123d as bd
from OCP.TopoDS import TopoDS_Shape

if not hasattr(TopoDS_Shape, "HashCode"):
    def _topods_shape_hash_code(self, upper_bound):
        return hash(self) % upper_bound

    TopoDS_Shape.HashCode = _topods_shape_hash_code
project_dir = Path.cwd()
export_format = sys.argv[1].lower()
quality_arg = sys.argv[2].lower() if len(sys.argv) > 2 else None
output_path = project_dir / f"output.{export_format}"
env = {"bd": bd, "build123d": bd}

project_dir_str = str(project_dir.resolve())
if project_dir_str not in sys.path:
    sys.path.insert(0, project_dir_str)

try:
    design_file = project_dir / "design.py"
    if not design_file.exists():
        raise RuntimeError("design.py not found in project. Cannot compile.")

    exec(design_file.read_text(encoding="utf-8"), env)

    shapes = []
    for val in env.values():
        if isinstance(val, bd.Shape) and hasattr(val, "volume"):
            geom_type = val.geom_type() if callable(val.geom_type) else val.geom_type
            geom_name = getattr(geom_type, "name", str(geom_type)).upper()
            if geom_name in ("SOLID", "COMPOUND", "OTHER"):
                shapes.append(val)
        elif hasattr(val, "part") and isinstance(getattr(val, "part"), bd.Shape):
            shapes.append(val.part)

    if not shapes and hasattr(bd.BuildPart, "_get_context") and bd.BuildPart._get_context():
        shapes.append(bd.BuildPart._get_context().part)

    if not shapes:
        raise RuntimeError("No 3D shapes (Solid/Part) were generated by the script.")

    final_shapes = []
    seen = set()
    for shape in shapes:
        if id(shape) not in seen:
            seen.add(id(shape))
            final_shapes.append(shape)

    compound = bd.Compound(final_shapes) if len(final_shapes) > 1 else final_shapes[0]
    if export_format == "stl":
        bd.export_stl(compound, str(output_path))
    elif export_format == "step":
        bd.export_step(compound, str(output_path))
    elif export_format in ("gltf", "glb") and hasattr(bd, "export_gltf"):
        deflection = 0.001
        if quality_arg == "sketch":
            deflection = 200.0
        elif quality_arg == "rough":
            deflection = 100.0
        elif quality_arg == "low":
            deflection = 50.0
        elif quality_arg == "medium":
            deflection = 30.0
        elif quality_arg == "normal":
            deflection = 10.0
        elif quality_arg == "high":
            deflection = 1.0

        bd.export_gltf(
            compound,
            str(output_path),
            binary=(export_format == "glb"),
            linear_deflection=deflection,
            angular_deflection=0.1
        )

        if export_format == "glb":
            try:
                from build123d.exporters3d import _create_xde
                from OCP.XCAFDoc import XCAFDoc_DocumentTool
                from OCP.TCollection import TCollection_AsciiString
                from OCP.TDF import TDF_Tool
                import json
                import struct

                # 1. Map tags to labels
                original_location = compound.location
                compound.location *= bd.Location((0, 0, 0), (1, 0, 0), -90)
                doc = _create_xde(compound, getattr(bd, "Unit").MM)
                shape_tool = XCAFDoc_DocumentTool.ShapeTool_s(doc.Main())
                tag_to_name = {}
                tag_to_color = {}

                for node in bd.PreOrderIter(compound):
                    if node.label or node.color is not None:
                        inst_label = shape_tool.FindShape(node.wrapped, findInstance=True)
                        if inst_label.IsNull():
                            inst_label = shape_tool.FindShape(node.wrapped, findInstance=False)

                        if not inst_label.IsNull():
                            entry = TCollection_AsciiString()
                            TDF_Tool.Entry_s(inst_label, entry)
                            tag = f"=>[{entry.ToCString()}]"
                            if node.label:
                                tag_to_name[tag] = node.label
                            if node.color is not None:
                                # Provide an sRGB list, e.g. [R, G, B, A]
                                tag_to_color[tag] = [
                                    node.color.wrapped.GetRGB().Red(),
                                    node.color.wrapped.GetRGB().Green(),
                                    node.color.wrapped.GetRGB().Blue(),
                                    node.color.wrapped.Alpha()
                                ]

                compound.location = original_location

                # 2. Patch the .glb files
                def patch_glb_metadata(glb_path, name_mapping, color_mapping):
                    if not name_mapping and not color_mapping:
                        return
                    with open(glb_path, "rb") as f:
                        data = f.read()

                    magic, version, length = struct.unpack("<4sII", data[:12])
                    if magic != b"glTF":
                        return

                    chunk_len, chunk_type = struct.unpack("<I4s", data[12:20])
                    if chunk_type != b"JSON":
                        return

                    json_data = data[20:20 + chunk_len].decode("utf-8")
                    gltf_json = json.loads(json_data)

                    changed = False
                    for material in gltf_json.get("materials", []):
                        pbr = material.get("pbrMetallicRoughness")
                        if isinstance(pbr, dict) and "baseColorFactor" in pbr:
                            extras = material.setdefault("extras", {})
                            if extras.get("tertiusAuthoredColor") is not True:
                                extras["tertiusAuthoredColor"] = True
                                changed = True

                    for node in gltf_json.get("nodes", []):
                        node_name = node.get("name")
                        if not node_name:
                            continue

                        # OCP often exports node names in the form of tag or something else. 
                        # Or it embeds the tag. The user code looks for the exact tag.
                        node_tag = node_name
                        if node_tag in color_mapping:
                            mesh_index = node.get("mesh")
                            if mesh_index is not None:
                                meshes = gltf_json.get("meshes", [])
                                if isinstance(mesh_index, int) and 0 <= mesh_index < len(meshes):
                                    mesh = meshes[mesh_index]
                                    primitives = mesh.get("primitives", [])
                                    if primitives and isinstance(primitives, list):
                                        material_index = primitives[0].get("material")
                                        materials = gltf_json.get("materials", [])
                                        if isinstance(material_index, int) and 0 <= material_index < len(materials):
                                            material = materials[material_index]
                                            pbr = material.setdefault("pbrMetallicRoughness", {})
                                            pbr["baseColorFactor"] = color_mapping[node_tag]
                                            extras = material.setdefault("extras", {})
                                            extras["tertiusAuthoredColor"] = True
                                            changed = True
                        if node_tag in name_mapping:
                            node["name"] = name_mapping[node_tag]
                            changed = True

                    if not changed:
                        return

                    new_json_data = json.dumps(gltf_json, separators=(',', ':')).encode("utf-8")
                    padding = (4 - len(new_json_data) % 4) % 4
                    new_json_data += b' ' * padding

                    new_chunk_len = len(new_json_data)
                    new_length = length - chunk_len + new_chunk_len

                    new_data = bytearray()
                    new_data.extend(struct.pack("<4sII", magic, version, new_length))
                    new_data.extend(struct.pack("<I4s", new_chunk_len, chunk_type))
                    new_data.extend(new_json_data)
                    new_data.extend(data[20 + chunk_len:])

                    with open(glb_path, "wb") as f:
                        f.write(new_data)

                patch_glb_metadata(str(output_path), tag_to_name, tag_to_color)
            except Exception as patch_e:
                print("Failed to patch GLB names:", patch_e)
    elif export_format == "timus_views":
        import json
        from OCP.HLRBRep import HLRBRep_PolyAlgo, HLRBRep_PolyHLRToShape
        from OCP.gp import gp_Ax2, gp_Pnt, gp_Dir, gp_Pnt2d
        from OCP.BRepMesh import BRepMesh_IncrementalMesh
        from OCP.TopExp import TopExp_Explorer
        from OCP.TopAbs import TopAbs_SOLID
        from OCP.TopoDS import TopoDS_Compound
        from OCP.BRep import BRep_Builder
        from OCP.BRepBndLib import BRepBndLib
        from OCP.Bnd import Bnd_Box
        from OCP.HLRAlgo import HLRAlgo_Projector

        # 1. Output parameters
        scale = 0.02
        settings_path = project_dir / "settings.json"
        if settings_path.exists():
            try:
                with open(settings_path) as f:
                    settings = json.load(f)
                    scale = settings.get("scale", 0.02)
            except Exception:
                pass
                
        line_weight_mm = 0.2
        min_model_size = line_weight_mm / scale
        deflection = min_model_size / 2.0

        # 2. Cull tiny geometry
        builder = BRep_Builder()
        culled_compound = TopoDS_Compound()
        builder.MakeCompound(culled_compound)

        explorer = TopExp_Explorer(compound.wrapped, TopAbs_SOLID)
        while explorer.More():
            solid = explorer.Current()
            bbox_obj = Bnd_Box()
            BRepBndLib.Add_s(solid, bbox_obj)
            xmin, ymin, zmin, xmax, ymax, zmax = bbox_obj.Get()
            max_dim = max(xmax - xmin, ymax - ymin, zmax - zmin)
            
            if max_dim >= min_model_size:
                builder.Add(culled_compound, solid)
            explorer.Next()
            
        # 3. Analytic HLR projection on culled model
        culled_bd = bd.Compound(culled_compound)
        bbox = culled_bd.bounding_box()
        look_at = bbox.center()
        max_dim = max(bbox.max.X - bbox.min.X, bbox.max.Y - bbox.min.Y, bbox.max.Z - bbox.min.Z)
        if max_dim == 0:
            max_dim = 100
            
        views = {}
        for view_name in ["top", "front", "side", "iso"]:
            if view_name == "top":
                origin = (look_at.X, look_at.Y, bbox.max.Z + max_dim)
                up_dir = (0, 1, 0)
            elif view_name == "front":
                origin = (look_at.X, bbox.min.Y - max_dim, look_at.Z)
                up_dir = (0, 0, 1)
            elif view_name == "side":
                origin = (bbox.max.X + max_dim, look_at.Y, look_at.Z)
                up_dir = (0, 0, 1)
            else:
                origin = (look_at.X + max_dim, look_at.Y - max_dim, look_at.Z + max_dim)
                up_dir = (0, 0, 1)
                
            try:
                visible, hidden = culled_bd.project_to_viewport(
                    origin, 
                    viewport_up=up_dir, 
                    look_at=(look_at.X, look_at.Y, look_at.Z)
                )
                
                segments = []
                
                def extract_edges(shape_list, is_hidden):
                    if not shape_list: return
                    for shape in shape_list:
                        for edge in shape.edges():
                            try:
                                if edge.geom_type.name == 'LINE':
                                    p1 = edge.position_at(0)
                                    p2 = edge.position_at(1)
                                    segments.append(((p1.X, p1.Y), (p2.X, p2.Y), is_hidden))
                                else:
                                    num_samples = max(8, min(64, int(edge.length / 2.0)))
                                    pts = [edge.position_at(i / num_samples) for i in range(num_samples + 1)]
                                    for i in range(len(pts)-1):
                                        p1, p2 = pts[i], pts[i+1]
                                        segments.append(((p1.X, p1.Y), (p2.X, p2.Y), is_hidden))
                            except Exception:
                                pass

                extract_edges(visible, False)
                extract_edges(hidden, True)
                            
                views[view_name] = segments
            except Exception as e:
                print(f"Failed to project {view_name}: {e}")
                views[view_name] = []

        with open(str(output_path), "w") as f:
            json.dump(views, f)
    else:
        raise RuntimeError(f"Unsupported export format: {export_format}")
except Exception:
    traceback.print_exc()
    sys.exit(1)
"""


@dataclass(frozen=True)
class CompileSandboxResult:
    success: bool
    output_path: Path | None
    stdout: str
    stderr: str
    error: str | None


def run_compile_sandbox(project_dir: Path, export_format: str, quality: str | None = None, timeout_seconds: int = 30) -> CompileSandboxResult:
    ext = export_format.lower()
    output_path = project_dir / f"output.{ext}"
    args = [sys.executable, "-c", SANDBOX_SCRIPT, ext]
    if quality:
        args.append(quality)

    try:
        result = subprocess.run(
            args,
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=exc.stdout or "",
            stderr=exc.stderr or "",
            error=f"Compile timed out after {timeout_seconds} seconds",
        )

    if result.returncode != 0:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=result.stderr.strip() or f"Compile exited with status {result.returncode}",
        )

    if not output_path.exists():
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=f"Compile completed without creating output.{ext}",
        )

    return CompileSandboxResult(
        success=True,
        output_path=output_path,
        stdout=result.stdout,
        stderr=result.stderr,
        error=None,
    )
