from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


SANDBOX_SCRIPT = r"""
import os
import sys
import traceback
from pathlib import Path

import build123d as bd

project_dir = Path.cwd()
export_format = sys.argv[1].lower()
output_path = project_dir / f"output.{export_format}"
env = {"bd": bd, "build123d": bd}

project_dir_str = str(project_dir.resolve())
if project_dir_str not in sys.path:
    sys.path.insert(0, project_dir_str)

try:
    design_file = project_dir / "design.py"
    if not design_file.exists():
        raise RuntimeError("design.py not found in project. Cannot compile.")

    exec(design_file.read_text(encoding="utf-8"), env)

    shapes = []
    for val in env.values():
        if isinstance(val, bd.Shape) and hasattr(val, "volume"):
            geom_type = val.geom_type() if callable(val.geom_type) else val.geom_type
            geom_name = getattr(geom_type, "name", str(geom_type)).upper()
            if geom_name in ("SOLID", "COMPOUND", "OTHER"):
                shapes.append(val)
        elif hasattr(val, "part") and isinstance(getattr(val, "part"), bd.Shape):
            shapes.append(val.part)

    if not shapes and hasattr(bd.BuildPart, "_get_context") and bd.BuildPart._get_context():
        shapes.append(bd.BuildPart._get_context().part)

    if not shapes:
        raise RuntimeError("No 3D shapes (Solid/Part) were generated by the script.")

    final_shapes = []
    seen = set()
    for shape in shapes:
        if id(shape) not in seen:
            seen.add(id(shape))
            final_shapes.append(shape)

    compound = bd.Compound(final_shapes) if len(final_shapes) > 1 else final_shapes[0]
    if export_format == "stl":
        bd.export_stl(compound, str(output_path))
    elif export_format == "step":
        bd.export_step(compound, str(output_path))
    elif export_format == "gltf" and hasattr(bd, "export_gltf"):
        bd.export_gltf(compound, str(output_path))
    else:
        raise RuntimeError(f"Unsupported export format: {export_format}")
except Exception:
    traceback.print_exc()
    sys.exit(1)
"""


@dataclass(frozen=True)
class CompileSandboxResult:
    success: bool
    output_path: Path | None
    stdout: str
    stderr: str
    error: str | None


def run_compile_sandbox(project_dir: Path, export_format: str, timeout_seconds: int = 30) -> CompileSandboxResult:
    ext = export_format.lower()
    output_path = project_dir / f"output.{ext}"
    try:
        result = subprocess.run(
            [sys.executable, "-c", SANDBOX_SCRIPT, ext],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=exc.stdout or "",
            stderr=exc.stderr or "",
            error=f"Compile timed out after {timeout_seconds} seconds",
        )

    if result.returncode != 0:
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=result.stderr.strip() or f"Compile exited with status {result.returncode}",
        )

    if not output_path.exists():
        return CompileSandboxResult(
            success=False,
            output_path=None,
            stdout=result.stdout,
            stderr=result.stderr,
            error=f"Compile completed without creating output.{ext}",
        )

    return CompileSandboxResult(
        success=True,
        output_path=output_path,
        stdout=result.stdout,
        stderr=result.stderr,
        error=None,
    )
