apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: tertius-web
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: tertius-web
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore: update deployed image tags

        {{range .Changed.Objects}}{{println .}}{{end}}
    push:
      branch: flux-image-updates
  update:
    path: ./charts/tertius
    strategy: Setters
